#!/bin/bash

function _rootgit_eval_gitter()
{
	if [[ -z "$GITTER" ]]; then
		GITTER=`who am i | awk '{ print $1; }'`
		if [[ "$GITTER" = "root" ]]; then
			unset GITTER
		fi
	fi
}

function _rootgit_prompt_gitter()
{
	_ROOTGIT_GITTERPATTERN="^[^<]+<[^@]+@[^>]+>$"
	until [[ -n $GITTER && $GITTER =~ $_ROOTGIT_GITTERPATTERN ]]; do
		read -e -i "$GITTER" -p "Please identify yourself in the format: First Last <user@domain.tld>" GITTER
	done
	unset _ROOTGIT_GITTERPATTERN
}

function _rootgit_try_git_commit()
{
	_ROOTGIT_COMMIT_PATTERN="no author found"
	_ROOTGIT_COMMIT_RET="$(\git commit "$@" --author "$GITTER")"
	echo "${_ROOTGIT_COMMIT_RET}"
	if [[ $_ROOTGIT_COMMIT_RET =~ $_ROOTGIT_COMMIT_PATTERN ]]; then
		unset _ROOTGIT_COMMIT_PATTERN
		unset _ROOTGIT_COMMIT_RET
		return 1
	else
		unset _ROOTGIT_COMMIT_PATTERN
		unset _ROOTGIT_COMMIT_RET
		return 0
	fi
}

function rootgit()
{
	if [[ "$1" = "commit" ]]; then
		_rootgit_eval_gitter
		if [[ -z "$GITTER" ]]; then
			_rootgit_prompt_gitter
		fi
		_rootgit_try_git_commit "${@:2}"
		if [[ $? -ne 0 ]]; then
			_rootgit_prompt_gitter
			_rootgit_try_git_commit "${@:2}"
		fi
	else
		\git "$@"
	fi
}
